# Generated by Django 4.0.6 on 2022-07-06 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicUsageRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField()),
                ('minimum', models.FloatField()),
                ('maximum', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PartnershipCostRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('minimum', models.FloatField()),
                ('maximum', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BiddingVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('sellercommission', models.FloatField()),
                ('fixedstoragerate', models.FloatField()),
                ('basicusagerate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.basicusagerate')),
                ('partnershipcostranges', models.ManyToManyField(to='administrator.partnershipcostrange')),
            ],
        ),
        migrations.CreateModel(
            name='BiddingCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('calculationdate', models.DateField()),
                ('biddingvariables', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.biddingvariable')),
            ],
        ),
    ]
